services:
  postgres-dev:
    container_name: "postgres-dev"
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env.test
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  mailcatcher:
    container_name: "mailcatcher-dev"
    image: "sj26/mailcatcher:v0.10.0"
    ports:
      - "1025:1025"
      - "1080:1080"
